"""Kiwoom API defaults exposed by configuration category."""

from .base import Config

KIWOOM_LIVE_REST_API_BASE_URL = Config.KIWOOM_LIVE_REST_API_BASE_URL
KIWOOM_MOCK_REST_API_BASE_URL = Config.KIWOOM_MOCK_REST_API_BASE_URL
KIWOOM_LIVE_WEBSOCKET_URL = Config.KIWOOM_LIVE_WEBSOCKET_URL
KIWOOM_MOCK_WEBSOCKET_URL = Config.KIWOOM_MOCK_WEBSOCKET_URL
REST_API_BASE_URL = Config.REST_API_BASE_URL
WEBSOCKET_URL = Config.WEBSOCKET_URL
TOKEN_CACHE_FILE = Config.TOKEN_CACHE_FILE

__all__ = [
    "KIWOOM_LIVE_REST_API_BASE_URL",
    "KIWOOM_MOCK_REST_API_BASE_URL",
    "KIWOOM_LIVE_WEBSOCKET_URL",
    "KIWOOM_MOCK_WEBSOCKET_URL",
    "REST_API_BASE_URL",
    "WEBSOCKET_URL",
    "TOKEN_CACHE_FILE",
]
