"""Market-intelligence defaults exposed by configuration category."""

from .base import Config

DEFAULT_MARKET_INTELLIGENCE_CONFIG = Config.DEFAULT_MARKET_INTELLIGENCE_CONFIG
DEFAULT_MARKET_INTEL_STATE = Config.DEFAULT_MARKET_INTEL_STATE
MARKET_INTELLIGENCE_HIGH_RISK_KEYWORDS = Config.MARKET_INTELLIGENCE_HIGH_RISK_KEYWORDS
MARKET_INTELLIGENCE_POSITIVE_KEYWORDS = Config.MARKET_INTELLIGENCE_POSITIVE_KEYWORDS
MARKET_INTELLIGENCE_NEGATIVE_KEYWORDS = Config.MARKET_INTELLIGENCE_NEGATIVE_KEYWORDS
MARKET_INTELLIGENCE_EVENT_KEYWORDS = Config.MARKET_INTELLIGENCE_EVENT_KEYWORDS
MARKET_INTELLIGENCE_EVENTS_FILE = Config.MARKET_INTELLIGENCE_EVENTS_FILE
MARKET_INTELLIGENCE_DECISION_AUDIT_FILE = Config.MARKET_INTELLIGENCE_DECISION_AUDIT_FILE

__all__ = [
    "DEFAULT_MARKET_INTELLIGENCE_CONFIG",
    "DEFAULT_MARKET_INTEL_STATE",
    "MARKET_INTELLIGENCE_HIGH_RISK_KEYWORDS",
    "MARKET_INTELLIGENCE_POSITIVE_KEYWORDS",
    "MARKET_INTELLIGENCE_NEGATIVE_KEYWORDS",
    "MARKET_INTELLIGENCE_EVENT_KEYWORDS",
    "MARKET_INTELLIGENCE_EVENTS_FILE",
    "MARKET_INTELLIGENCE_DECISION_AUDIT_FILE",
]
