"""Risk-management defaults exposed by configuration category."""

from .base import Config

DEFAULT_MAX_DAILY_LOSS = Config.DEFAULT_MAX_DAILY_LOSS
DEFAULT_MAX_HOLDINGS = Config.DEFAULT_MAX_HOLDINGS
DEFAULT_USE_RISK_MGMT = Config.DEFAULT_USE_RISK_MGMT
DEFAULT_DAILY_LOSS_BASIS = Config.DEFAULT_DAILY_LOSS_BASIS
DEFAULT_USE_SHOCK_GUARD = Config.DEFAULT_USE_SHOCK_GUARD
DEFAULT_USE_VI_GUARD = Config.DEFAULT_USE_VI_GUARD
DEFAULT_USE_REGIME_SIZING = Config.DEFAULT_USE_REGIME_SIZING
DEFAULT_USE_LIQUIDITY_STRESS_GUARD = Config.DEFAULT_USE_LIQUIDITY_STRESS_GUARD
DEFAULT_USE_SLIPPAGE_GUARD = Config.DEFAULT_USE_SLIPPAGE_GUARD
DEFAULT_USE_ORDER_HEALTH_GUARD = Config.DEFAULT_USE_ORDER_HEALTH_GUARD

__all__ = [
    "DEFAULT_MAX_DAILY_LOSS",
    "DEFAULT_MAX_HOLDINGS",
    "DEFAULT_USE_RISK_MGMT",
    "DEFAULT_DAILY_LOSS_BASIS",
    "DEFAULT_USE_SHOCK_GUARD",
    "DEFAULT_USE_VI_GUARD",
    "DEFAULT_USE_REGIME_SIZING",
    "DEFAULT_USE_LIQUIDITY_STRESS_GUARD",
    "DEFAULT_USE_SLIPPAGE_GUARD",
    "DEFAULT_USE_ORDER_HEALTH_GUARD",
]
