"""Strategy defaults exposed by configuration category."""

from .base import Config

DEFAULT_STRATEGY_PACK = Config.DEFAULT_STRATEGY_PACK
DEFAULT_STRATEGY_PARAMS = Config.DEFAULT_STRATEGY_PARAMS
DEFAULT_PORTFOLIO_MODE = Config.DEFAULT_PORTFOLIO_MODE
DEFAULT_EXECUTION_POLICY = Config.DEFAULT_EXECUTION_POLICY
DEFAULT_EXECUTION_MODE = Config.DEFAULT_EXECUTION_MODE
EXECUTION_MODES = Config.EXECUTION_MODES
STRATEGY_CAPABILITIES = Config.STRATEGY_CAPABILITIES

__all__ = [
    "DEFAULT_STRATEGY_PACK",
    "DEFAULT_STRATEGY_PARAMS",
    "DEFAULT_PORTFOLIO_MODE",
    "DEFAULT_EXECUTION_POLICY",
    "DEFAULT_EXECUTION_MODE",
    "EXECUTION_MODES",
    "STRATEGY_CAPABILITIES",
]
